---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-kubernetes-example
  annotations:
    github.com/project-slug: ciiay/backstage-kubernetes-example
spec:
  type: other
  lifecycle: unknown
  owner: ciiay
---
