apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: test-day
  description: The RHDH UI test group
spec:
  type: team
  profile:
    displayName: RHDH UI test day
    email: test1@example.com
  children: []
  members: [test1, test2]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admins
  description: Administrator group
spec:
  type: team
  profile:
    displayName: Admins
  children: []
  members: [test1]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: test1
spec:
  profile:
    displayName: Test One
    email: test1@example.com
  memberOf:
    - test-day
    - admins

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: test2@example.com
spec:
  profile:
    email: test2@123
  memberOf:
    - test-day
