apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
    backstage.io/kubernetes-label-selector: 'app=my-app,component=front-end'
spec:
  lifecycle: production
  owner: my-team
  type: service
